### PR TITLE
Fixed and simplified the assertion handling logic: even with flatten …

### PR DESCRIPTION
**Pull request by psiha**
…and forceinline allover pure debug codegen is still larger for the entupling-delayed-streaming approach compared to inline streaming operator calls.

### CODE REVIEW

**Comment by jfalcou** [comment]
So, what does this PR fix ?
I see kumi fixes but you end up not using tuple anymore ?
What shoudl we do with this ?

Could the kumi changes be PR'ed over at kumi ?

**Comment by psiha** [comment]
> So, what does this PR fix ?

'Source location' parameters were incorrectly propagated (e.g. the location would always be the assert helper function 🙈 😊)

> I see kumi fixes but you end up not using tuple anymore ? What shoudl we do with this ?

The other issue was the bloated code generated by my previous changes - the kumi changes (forceinlines and all that) were attempts to workaround that - however it wasn't enough - so I gutted the 'entuplment' shenanigans alltogether - but left the kumi changes for you to choose if perhaps you want them anyway...

> Could the kumi changes be PR'ed over at kumi ?

As you like, I can remove them from the PR alltogether.

**Comment by jfalcou** [comment]
OK, I'm for : 
 + you remove the kumi fixes and make a kumi PR or issur for them
 + we merge the rest 
 ?

Are you OK now with the gen code btw ?

**Comment by psiha** [comment]
> * kumi PR or issur for them

pr on the separate repo for kumi library or on this repo just a separate pr for that file alone?

**Comment by psiha** [comment]
> Last thing too. Can't `BOOST_ENABLE_ASSERT_HANDLER` be `KWK_ENABLE_ASSERT_HANDLER` ? Then we ifdef BOOST_ENABLE_ASSERT_HANDLER to set the other macro up ?

not sure what you mean - i use BOOST_ENABLE_ASSERT_HANDLER to detect if the user is using Boost.Assert machinery - i.e. has potentially setup a custom assertion handler (boost::assertion_failed_msg) and then respect that by delegating the final handling of the assertion failure to that handler

**Comment by psiha** [comment]
> Are you OK now with the gen code btw ?

never(tm) 😅  ... but enough that i'm not going to spend more time on it (ideally the macro invocations would all have to be changed which, i suppose, is not worth the effort)

**Comment by jfalcou** [comment]
> not sure what you mean - i use BOOST_ENABLE_ASSERT_HANDLER to detect if the user is using Boost.Assert machinery - i.e. has potentially setup a custom assertion handler (boost::assertion_failed_msg) and then respect that by delegating the final handling of the assertion failure to that handler

I mean we don't depends on BOOST so requriign user to overload BOOST_ENABLE_ASSERT_HANDLER is strange. We can keep the same internal mecanism but ties up to a KWK_ macro.

**Comment by jfalcou** [comment]
AAAAH no wait I see what is going on. So, no that's OK.

**Pull request merged**
